project_id = "wtpmxuhkbwwiougblkki"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.knowledge-vault-chat]
verify_jwt = false

[functions.parse-vault-file]
verify_jwt = false

[functions.migrate-vault-files]
verify_jwt = true

[functions.simple-vault-chat]
verify_jwt = true

[functions.semantic-cache]
verify_jwt = false

[functions.smart-alerts]
verify_jwt = false

[functions.capture-screenshot]
verify_jwt = true

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "dual"
port = 54324

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1s"

[auth.sms]
enable_signup = false
enable_confirmations = false
max_frequency = "5s"

[edge_runtime]
enabled = true
port = 54330